name = "my-project-my-success"
main = "worker/index.js"
compatibility_date = "2024-12-01"
workers_dev = true

[durable_objects]
bindings = [
  { name = "USER_SESSION", class_name = "UserSession" },
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["UserSession", "ChatRoom"]

[vars]
ENVIRONMENT = "production"
