name = "chatgram-api"
main = "index.js"
compatibility_date = "2026-01-16"

[vars]
APP_NAME = "Chatgram"

[[kv_namespaces]]
binding = "USERS"
id = "PUT_YOUR_KV_ID"

[[kv_namespaces]]
binding = "SESSIONS"
id = "PUT_YOUR_KV_ID"

[[kv_namespaces]]
binding = "CHATS"
id = "PUT_YOUR_KV_ID"

[[kv_namespaces]]
binding = "MESSAGES"
id = "PUT_YOUR_KV_ID"
